### ISSUE TITLE
False-positive crash restart

### ISSUE THREAD

**Issue by Theepwner** [mark2devel/mark2#158]
My bungeecord is on a restart loop because mark2 can't ping the ip due to TCPShield plugin denying connections to it unless they first go through their proxy (i.e. the domains connected to them). Is there a way to disable the below feature? 

```
2021-11-15 22:14:47 # server might have crashed: not accepting connections or wrong port is being pinged. -- restarting.
2021-11-15 22:14:47 # stopping bungee (caused by not accepting connections)
2021-11-15 22:14:47 | Closing listener [id: 0x8555ce38, L:/[0:0:0:0:0:0:0:0%0]:25565]
2021-11-15 22:14:47 | Closing listener [id: 0xa1bcdc0f, L:/[0:0:0:0:0:0:0:0%0]:25565]
2021-11-15 22:14:47 | Closing pending connections
2021-11-15 22:14:47 | Disconnecting 2 connections
```

**Comment by Theepwner** [comment]
I see that the server.properties is supposed to be address this, but what if I don't have a workable ip I can put there?

**Comment by Column01** [comment]
I believe that TCPShield will not work with mark2. There is some code in TCPShield to drop ping attempts if they are from a legacy server list ping which mark2 uses for compatibility reasons. I will see if I can potentially implement a newer server list ping protocol, but no promises.

See the TCP shield code [here](https://github.com/TCPShield/RealIP/blob/cf97e376323f5fcdd0f2113d11007922dbb8d024/src/main/java/net/tcpshield/tcpshield/bungee/handler/BungeeHandshakeHandler.java#L24-L31)

**Comment by Column01** [comment]
In order to implement it, we'd need some way to determine if the server it's pinging is 1.6 or newer. In 1.7, the ping protocol was changed in a breaking way. TCPShield detects that change (well really bungeecord does) and then drops all "legacy" ping requests AKA mark2's ping request.

Ironically, I found [code](https://gist.github.com/barneygale/1209061) from one of the OG mark2 developers that he made 5 months ago to ping newer Minecraft servers lol

Will probably look into an elegant way of using it in mark2 to hopefully fix this issue

**Comment by Column01** [comment]
I've started working on a new project for server wrapping in Python instead of doing this. Looking at the code, it would have been possible to implement it in the existing project, but difficult given certain limitations in regard to compatibility, going to close this as technically it's TCPShield breaking mojang convention by denying legacy pings (even though the new project will follow the new standard)

**Comment by TomLewis** [comment]
I fell into this problem today trying to setup TCPShield and mark2 just restarting the proxy over and over again.
