### ISSUE TITLE
"Too many open files" and cannot access running server. 

### ISSUE THREAD

**Issue by TomLewis** [mark2devel/mark2#162]
![Screenshot 2021-12-16 at 12 32 53](https://user-images.githubusercontent.com/144046/146373721-d3007249-b941-4b9a-a0bc-6fff3cc0f383.png)

I run `mark2 start` on a sever that had a plugin doing a large conversion, so the startup window was still open in my terminal, then about an hour or two later I look back and its errored out with this and I can no longer attach to the server to see how the conversions going on, it still appears in mark2 list and it appears at the top menu bar, but when I go to attach it shows the server before it.

Edit: I cannot kill the server...
Edit Edit: Had to kill it via system.

**Comment by Column01** [comment]
You should check how many open files you are allowed in your operating system by using: `ulimit -n` and you can up the limit using `ulimit -n 2048`. In my case, Ubuntu 18 reported a max number of open files as `1024` which I haven't a clue how you'd hit that number. The limit is apparently user-based too so if you have a lot of stuff running under one user, you should probably divvy it up (E.G. Web server, discord bots and other junk under different users)

This isn't a bug with mark2, but something inherent in your setup causing you to hit the max open files. Unless you can somehow point to something in mark2 opening thousands of files that is 😉. Since there is nothing for me to fix, I'll have to close this for now (again, unless you can find something specific to mark2 causing it)
